config/routes.rb
Rails.application.routes.draw do

  get 'dashboards/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'lobbies#index'

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :topups, only: [:index, :show, :new, :create]

  resources :orders, only: [:show, :new, :create] do
    resources :payments, only: :new
  end

  resources :lobbies, only: [:show] do
    resources :sessions, only: [:index, :show, :new, :create, :destroy] do
      resources :messages, only: [:create, :destroy]
      resources :user_invites, only: [:create, :update]
    end
  end

  get "/dashboard" , to: "dashboards#show"  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/components", to: "pages#components"

  patch '/join', to: "sessions#joining_session"
  patch "/accept", to: "user_invites#accept"
  patch "/cancel", to: "user_invites#cancel"
  patch "/decline", to: "user_invites#decline"

  delete "/delete", to: "user_invite#destroy"

  patch '/score', to: "sessions#submit_score"

  patch '/agreed', to: "sessions#agreed"


end

app/models/lobby.rb
class Lobby < ApplicationRecord
  has_many :messages, as: :messageable
  has_many :user_lobbies
  has_many :users, through: :user_lobbies
  has_many :sessions

  # this validation is ok, but you can add more
  # Also all the models should have more validations
  validates :title, presence: true
end

app/controllers/lobbies_controller.rb
class LobbiesController < ApplicationController
  skip_before_action :authenticate_user!, only:[:index, :show]
  def index
    @lobbies = Lobby.all
  end

  def show
    @lobby = Lobby.find(params[:id])
    @sessions = Session.where(lobby_id: @lobby.id)
  end
end

app/views/lobbies/index.html.erb
<div class="banner" style="background-image: radial-gradient(circle, rgba(0,0,0,0) 64%, rgba(0,0,0,1) 90%), url(<%= asset_url 'couch.jpg' %>);">
  <div class="container">
    <h1>Are you the best? Bet on it!</h1>
    <p>Join our gaming couch and beef for any amount! </p>
    <a class="btn btn-flat" id="button">Play now!</a>
  </div>
</div>
<div class="container d-flex justify-content-center" style="margin-top: 100px;" >

    <div class="lobbies" id="lobby">
      <% @lobbies.each do |lobby| %>
      <%= render 'shared/card', lobby: lobby %>
      <% end %>
    </div>

</div>

    <%= render 'shared/footer' %>

app/views/lobbies/show.html.erb
<div class="game-banner" style="background-image:linear-gradient(0deg, rgba(0,0,0,1) 2%, rgba(0,0,0,1) 10%, rgba(0,0,0,0) 50%), url(<%= asset_url @lobby.photo %>);">
</div>
<div class="container">
    <%= link_to root_path, class:"btn-back" do %>
      <i class="fas fa-arrow-left" style="color: #f88a2b;"></i>
    <% end %>
  <h1 class="title"><%= @lobby.title.capitalize! %></h1>
  <h3 class="session">1 v 1 sessions</h3>
  <div class="cards-lobby-show">
  <% @sessions.each do |s| %>
    <% if s.status == "pending" %>
    <%= render 'shared/beefcard', session: s %>
    <% end %>
  <% end %>
  </div>
  <%= link_to "Create a beef", new_lobby_session_path(@lobby.id), class:"btn btn-flat-orange" %>
</div>