config/routes.rb
Rails.application.routes.draw do

  get 'dashboards/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'lobbies#index'

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :topups, only: [:index, :show, :new, :create]

  resources :orders, only: [:show, :new, :create] do
    resources :payments, only: :new
  end

  resources :lobbies, only: [:show] do
    resources :sessions, only: [:index, :show, :new, :create, :destroy] do
      resources :messages, only: [:create, :destroy]
      resources :user_invites, only: [:create, :update]
    end
  end

  get "/dashboard" , to: "dashboards#show"  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/components", to: "pages#components"

  patch '/join', to: "sessions#joining_session"
  patch "/accept", to: "user_invites#accept"
  patch "/cancel", to: "user_invites#cancel"
  patch "/decline", to: "user_invites#decline"

  delete "/delete", to: "user_invite#destroy"

  patch '/score', to: "sessions#submit_score"

  patch '/agreed', to: "sessions#agreed"


end

app/views/shared/_beefcard.html.erb
<div class="container card">
  <div class="beef-card" style="background: radial-gradient(circle, rgba(0,0,0,0) 0%, rgba(248,138,43,1) 100%);">
    <div class="beef-card-info"><p><% if session.custom_rules? %><%= "Custom rules" %><% else %><%= "Main rules" %><% end %></p><h2><%= session.price * 2 %>$</h2></div>
    <div class="beef-card-link"><%= link_to "Check beef", lobby_session_path(@lobby, session) %></div>
    <div class="beef-card-avatar"><%= cl_image_tag session.user.avatar %><h2><strong><%= session.user.username %></strong></h2></div>
  </div>
</div>

app/views/shared/_card.html.erb
<%= link_to lobby_path(lobby), class:"card-link" do %>
  <div class="card-lobby" style="margin-top: 60px ; border-radius: 20px;">
    <div class="card-image" style="background: rgb(2,0,36); background-image:linear-gradient(0deg, rgba(2,0,36,1) 0%, rgba(0,0,0,1) 2%, rgba(0,0,0,0) 50%), url(<%= asset_path lobby.photo %>); border-radius:10px; height:250px; background-size:cover; background-position: center;">
    </div>
    <div class="card-body card-body-lobby">
      <h5><%= lobby.title %></h5>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-5">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="main-navbar d-flex justify-content-between align-items-center px-3 py-1">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "beef.png" %>
  <% end %>
      <% if user_signed_in? %>
      <div class="d-flex align-items-center text-white">
        <%= link_to "", new_topup_path, class:"far fa-plus-square mr-2" =%>
     <div class="mr-2" style="font-size: 26px;" > <%= "$#{current_user.wallet}" %> </div>
  <div class="main-navbar-menu">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <%= link_to "Wallet: $#{current_user.wallet}", "#", class: "dropdown-item" %>
            <%= link_to "Dashboard", dashboard_path, method: :get, class: "dropdown-item" %>

            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <div class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link text-center" %>
        </div>
      <% end %>
    </ul>
  </div>
      </div>
</div>

app/views/shared/_sessionbeefcard.html.erb
<div class="container">
  <div class="beef-card" style="background: radial-gradient(circle, rgba(0,0,0,0) 0%, rgba(248,138,43,1) 100%);">
    <div class="beef-card-info-s" >
      <% if @session.status == "finished" %>
        <h2><%= @session.score1 %></h2>
        <h2>-</h2>
        <h2><%= @session.score2 %></h2>
      <% elsif (@session.user != current_user) && (@session.user_invites.any? { |invite| invite.user == current_user }) && ( @session.status == "pending" ) %>
        <p> <%= @session.status %> </p>
        <h2><%= @session.price * 2 %>$</h2>
      <% elsif @session.status == "in progress"%>
        <p>In progress</p>
        <h2><%= @session.win_price %>$</h2>
      <% elsif @session.status == "agreed" %>
          <% if current_user.username == @session.winner %>
        <h2><%= @session.score1 %></h2>
        <p style="color:green;">WON <%= @session.win_price %> </p>
        <h2><%= @session.score2 %></h2>
          <% else %>
        <h2><%= @session.score1 %></h2>
        <p style="color:red;">LOST <%= @session.price %> </p>
        <h2><%= @session.score2 %></h2>
          <% end %>
      <% else %>
        <p>Entry:<%= @session.price %>$</p>
        <h2><%= @session.price * 2 %>$</h2>
      <% end %>
    </div>
    <div class="beef-card-avatar"><%= cl_image_tag @session.user.avatar %><h3><%= @session.user.username %></h3></div>

  <% if (@session.status == "finished") %>
      <div class="beef-card-avatar-two"><h3 id="textx"><%= @session.user_invites.first.user.username%></h3><%= cl_image_tag @session.user_invites.first.user.avatar%></div>
    <% elsif (@session.user != current_user) && (@session.user_invites.any? { |invite| invite.user == current_user }) %>
      <div class="beef-card-avatar-two"><h3 id="textx"><%= current_user.username%></h3><%= cl_image_tag current_user.avatar%></div>
      <% elsif (@session.status == "in progress") && (current_user== @session.user)%>
      <div class="beef-card-avatar-two"><h3 id="textx"><%= @session.user_invites.first.user.username%></h3><%= cl_image_tag @session.user_invites.first.user.avatar%></div>
    <% end %>
  </div>
</div>