config/routes.rb
Rails.application.routes.draw do

  get 'dashboards/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: 'lobbies#index'

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :topups, only: [:index, :show, :new, :create]

  resources :orders, only: [:show, :new, :create] do
    resources :payments, only: :new
  end

  resources :lobbies, only: [:show] do
    resources :sessions, only: [:index, :show, :new, :create, :destroy] do
      resources :messages, only: [:create, :destroy]
      resources :user_invites, only: [:create, :update]
    end
  end

  get "/dashboard" , to: "dashboards#show"  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/components", to: "pages#components"

  patch '/join', to: "sessions#joining_session"
  patch "/accept", to: "user_invites#accept"
  patch "/cancel", to: "user_invites#cancel"
  patch "/decline", to: "user_invites#decline"

  delete "/delete", to: "user_invite#destroy"

  patch '/score', to: "sessions#submit_score"

  patch '/agreed', to: "sessions#agreed"


end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @mysessions = Session.where(user: current_user)
    @sent_invites = UserInvite.where(user: current_user).where(status: "Pending").select{|ui| ui.session.user_id == current_user.id}.map { |ui| ui.session }
    @received_invites = UserInvite.where(user: current_user).where(status: "Pending").select{|ui| ui.session.user_id != current_user.id}.map { |ui| ui.session }
    @accepted_sessions = UserInvite.where(user: current_user).where(status: "accepted").map { |ui| ui.session }
    @alls = @mysessions + @accepted_sessions
    @inprogresssessions = @alls.select { |session| session.status == "in progress" || session.status == "finished" }
    @finished_sessions = @alls.select { |session| session.status == "agreed" }
  end
end

app/views/dashboards/show.html.erb
<div class="container text-white">
  <br>
  <h5>Pending requests on my sessions</h5>
  <div class="row d-flex align-items-center dashboard-card" style="background: linear-gradient(90deg, rgba(50,50,50,1) 5%, rgba(235,235,235,0) 30%, rgba(255,255,255,0) 49%);">
    <% @mysessions.each do |session|%>
      <% if session.user_invites.select{|n| n.status == "Pending" }.first %>
          <div class="col-4">
            <div class="beef-card-avatar-dashboard">
              <%= cl_image_tag session.user_invites.first.user.avatar %>
            </div>
          </div>

        <div class="col-3">
                <h5 class="mt-2">  <%= session.price*2 %>$</h5>

                <%= session.user_invites.first.status %>
            </div>

            <div class="col-2">
            <%= link_to lobby_session_path(session.lobby, session), class:"d-flex align-items-center justify-content-between" do %>
                <i class="far fa-eye"></i>
            <% end %>
         </div>


      <div class="col-3 d-flex justify-content-between">
        <%= link_to accept_path(user_invite_id: session.user_invites.first.id, session_id: session.id), method: :patch, class:"d-flex justify-content-end" do %>
          <i class="fas fa-check" style="font-size: 20px; color: green;"></i>
        <% end %>
        <%= link_to decline_path(user_invite_id: session.user_invites.first.id, session_id: session.id), method: :patch, class:"d-flex justify-content-end" do %>
          <i class="fas fa-times" style="font-size: 20px; color: red;"></i>
        <% end %>
      </div>

      <% end %>
    <% end %>
  </div>
  <br>

  <h5>Sent invitations</h5>
  <div class="row d-flex align-items-center mt-3 dashboard-card" style="background: linear-gradient(90deg, rgba(50,50,50,1) 5%, rgba(235,235,235,0) 30%, rgba(255,255,255,0) 49%);">
    <% @sent_invites.each do |session|%>
      <div class="col-4">
        <div class="beef-card-avatar-dashboard">
          <%= cl_image_tag session.user.avatar %>
        </div>
      </div>

      <div class="col-3">
          <h5 class="mt-2">  <%= session.price %>$</h5>
          <%= session.user_invites.first.status %>
      </div>

      <div class="col-2">
        <%= link_to lobby_session_path(session.lobby, session), class:"d-flex align-items-center justify-content-between" do %>
          <i class="far fa-eye"></i>
        <% end %>
      </div>


     <% if current_user == session.user %>
        <div class="col-3 d-flex justify-content-between">
          <%= link_to accept_path(user_invite_id: session.user_invites.first.id, session_id: session.id), method: :patch, class:"d-flex justify-content-end" do %>
            <i class="fas fa-check" style="font-size: 20px; color: green;"></i>
          <% end %>
          <%= link_to decline_path(user_invite_id: session.user_invites.first.id, session_id: session.id), method: :patch, class:"d-flex justify-content-end" do %>
            <i class="fas fa-times" style="font-size: 20px; color: red;"></i>
          <% end %>
        </div>
        <% else %>
          <div class="col-3 d-flex justify-content-end">
            <%= link_to decline_path(user_invite_id: session.user_invites.first.id, session_id: session.id), method: :patch, class:"d-flex justify-content-end" do %>
              <i class="fas fa-times" style="font-size: 20px; color: red;"></i>
            <% end %>
          </div>
      <% end %>
    <% end %>
  </div>

  <h5>Received invitations</h5>
  <div class="row d-flex align-items-center mt-3 dashboard-card" style="background: linear-gradient(90deg, rgba(50,50,50,1) 5%, rgba(235,235,235,0) 30%, rgba(255,255,255,0) 49%);">
    <% @received_invites.each do |session|%>
      <div class="col-4">
        <div class="beef-card-avatar-dashboard">
          <%= cl_image_tag session.user.avatar %>
        </div>
      </div>

      <div class="col-3">
          <h5 class="mt-2">  <%= session.price %>$</h5>
          <%= session.user_invites.first.status %>
      </div>

      <div class="col-2">
        <%= link_to lobby_session_path(session.lobby, session), class:"d-flex align-items-center justify-content-between" do %>
          <i class="far fa-eye"></i>
        <% end %>
      </div>


     <% if current_user == session.user %>
        <div class="col-3 d-flex justify-content-between">
          <%= link_to accept_path(user_invite_id: session.user_invites.first.id, session_id: session.id), method: :patch, class:"d-flex justify-content-end" do %>
            <i class="fas fa-check" style="font-size: 20px; color: green;"></i>
          <% end %>
          <%= link_to decline_path(user_invite_id: session.user_invites.first.id, session_id: session.id), method: :patch, class:"d-flex justify-content-end" do %>
            <i class="fas fa-times" style="font-size: 20px; color: red;"></i>
          <% end %>
        </div>
        <% else %>
          <div class="col-3 d-flex justify-content-end">
            <%= link_to decline_path(user_invite_id: session.user_invites.first.id, session_id: session.id), method: :patch, class:"d-flex justify-content-end" do %>
              <i class="fas fa-times" style="font-size: 20px; color: red;"></i>
            <% end %>
          </div>
      <% end %>
    <% end %>
  </div>


  <br>
  <h5>My sessions in progress</h5>
    <div class="row d-flex align-items-center mt-3 dashboard-card" style="background: linear-gradient(90deg, rgba(50,50,50,1) 5%, rgba(235,235,235,0) 30%, rgba(255,255,255,0) 49%);">
    <% @inprogresssessions.each do |session|%>
      <div class="col-4">
        <div class="beef-card-avatar-dashboard">
            <%= cl_image_tag session.user_invites.first.user.avatar %>
        </div>
      </div>
      <div class="col-6">
          <h5 class="mt-2">  <%= session.price*2 %>$</h5>
          <%= session.status %>
      </div>
      <div class="col-2">
        <%= link_to lobby_session_path(session.lobby, session), class:"d-flex align-items-center justify-content-between" do %>
          <i class="far fa-eye"></i>
        <% end %>
      </div>
    <% end %>
  </div>

  <br>
  <h5>History of my past sessions</h5>
  <div class="row d-flex align-items-center mt-3 dashboard-card" style="background: linear-gradient(90deg, rgba(50,50,50,1) 5%, rgba(235,235,235,0) 30%, rgba(255,255,255,0) 49%);">
    <% @finished_sessions.each do |session|%>
      <div class="col-4">
        <div class="beef-card-avatar-dashboard">
            <%= cl_image_tag session.user_invites.first.user.avatar %>
        </div>
      </div>
      <div class="col-6">
        <% if session.winner == current_user.username %>
          <h5 class="mt-2" style="color:green;"> WON <%= session.price*2 %>$</h5>
        <% else %>
          <h5 class="mt-2" style="color:red;"> LOST <%= session.price %>$</h5>
        <% end %>
      </div>
      <div class="col-2">
        <%= link_to lobby_session_path(session.lobby, session), class:"d-flex align-items-center justify-content-between" do %>
          <i class="far fa-eye"></i>
        <% end %>
      </div>
    <% end %>
  </div>


</div>